### ISSUE TITLE
error

### ISSUE THREAD

**Issue by manvirvirk** [linjx-ustc1106/TuiGAN-PyTorch#3]
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[60, 1, 104, 101] to have 3 channels, but got 1 channels instead
whole traceback is:
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    train(opt, Gs, Zs, reals, NoiseAmp, Gs2, Zs2, reals2, NoiseAmp2)
  File "D:\TuiGAN-PyTorch-master\models\TuiGAN.py", line 72, in train
    z_curr,in_s,G_curr, z_curr2,in_s2,G_curr2 = train_single_scale(D_curr,G_curr, reals,Gs,Zs,in_s,NoiseAmp, D_curr2,G_curr2, reals2,Gs2,Zs2,in_s2,NoiseAmp2, opt,scale_num)
  File "D:\TuiGAN-PyTorch-master\models\TuiGAN.py", line 154, in train_single_scale
    output = netD(real2).to(opt.device)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\TuiGAN-PyTorch-master\models\model.py", line 36, in forward
    x = self.head(x)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\virkt\Anaconda3\envs\cgan\lib\site-packages\torch\nn\modules\conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[60, 1, 104, 101] to have 3 channels, but got 1 channels instead
please help

**Comment by linjx-ustc1106** [comment]
I think it is because your input only has 1 image channel, while the model requires images of 3 channel. You may modify your model's input channel number to 1 or you should input RGB image instead of gray image.

**Comment by manvirvirk** [comment]
@linjx-ustc1106 Thanks for help. My input images in trainA folder are grayscale while in trainB are rgb , is it possible to train? Where i can change input channel number in code as i checked code but did not find it.

**Comment by linjx-ustc1106** [comment]
> @linjx-ustc1106 Thanks for help. My input images in trainA folder are grayscale while in trainB are rgb , is it possible to train? Where i can change input channel number in code as i checked code but did not find it.

In our code, we default use the same input channel for trainA and trainB images (i.e., opt.nc_im).  In your case, you may creat an opt.nc_im1=1 and opt.nc_im2=3 for two generators and discriminators respectively.

**Comment by manvirvirk** [comment]
Thanks for the help. One last query can we produce more
fine(clearer,dilated) image at output?

**Comment by linjx-ustc1106** [comment]
It mostly depends on your training images sizes.

**Comment by manvirvirk** [comment]
Thanks for the help!
